### ISSUE TITLE
Bot no longer registering valid users 

### ISSUE THREAD

**Issue by samilawson** [ishwi/discordBot#19]
As of earlier today, the bot has stopped registering new (valid) users with their last fm, throwing the error message and instructing them to try using the update command instead. Existing users changing usernames was not affected, but I have several users who are completely new to the bot who are not able to set their last fm account. I suspect it’s a database issue, but I’m not sure.

**Comment by ishwi** [comment]
Thank you so much for your report. I recently changed all the database structure and even thought I tested it a lot I probably might have missed something. I'll take a look.
