### ISSUE TITLE
Bot can ping users/roles/everyone

### ISSUE THREAD

**Issue by th0mk** [ishwi/discordBot#21]
If it has permissions to ping everyone/here, it can be used for that.
![image](https://user-images.githubusercontent.com/9088316/76509540-77e6d800-6450-11ea-812b-450f858cca25.png)

 It can also ping users:
![image](https://user-images.githubusercontent.com/9088316/76509579-8af9a800-6450-11ea-8eb5-c692f675696c.png)

**Comment by ishwi** [comment]
Should be fixed now on #23 
Thank you very much for reporting the error.
