### ISSUE TITLE
Broken Markdown with unescaped characters in artist names

### ISSUE THREAD

**Issue by jackchen0226** [ishwi/discordBot#25]
Artist names with the '_' character may create a block of italicized text in Markdown. This in turn breaks any other Markdown formatting in between the underscore characters.

![image](https://user-images.githubusercontent.com/12056327/76919425-19718d80-6886-11ea-9df4-5c5fa7f72d80.png)

The artist nervous_testpilot starts an italicized block and coincidentally ends with with last.fm username SwitchyRabbit_ and breaking link formatting along the way.

Same issue would occur with other Markdown characters such as * or ~

**Comment by ishwi** [comment]
Thanks for reporting the bug. Had to change a lot of things to avoid any kind of trouble with markdown characters. If you still see any cases where the markdown gets weird feel free to reopen this issue.
