### ISSUE TITLE
AOTY command being kind of inaccurate?

### ISSUE THREAD

**Issue by RaylaLe100** [ishwi/discordBot#30]
Hi!
Sorry to write an issue about something that isn't really a bug, but with friends we thought that the command !aoty was kind of innaccurate because it will favor long albums over smaller ones. I thought maybe instead of the play count, you could make these charts with `play_count / album_number_of_tracks` ?
I honestly don't know if it's a good idea but it seems more accurate to me.

**Comment by ishwi** [comment]
I think is a good idea. I'll try to investigate if such thing is possible and if it is I'll maybe implement it as an extra flag on the command because I still thing most people would want the normal sorting.

**Comment by ishwi** [comment]
It doesn't work very well but its all I could do trying to make it a bit more accurate. Using --time should show sort the chart by the time field
