### ISSUE TITLE
Error with _Artist command

### ISSUE THREAD

**Issue by XpertShadow** [ishwi/discordBot#34]
Hello, When me or one of my server members do the _Artist command we either do not get any images of albums with scrobbles or we get 1album with its scrobbles. Im not sure if this is a issue to do with Last.fm or the bot. I have attached a image of the error.
Thanks
![liluziartist2](https://user-images.githubusercontent.com/67650194/86151492-b20ae100-baf6-11ea-9f2e-0ea8f3309940.png)

**Comment by ishwi** [comment]
This is due to the new album indexing that was added, so now the artist command resolves using the local database.So what is probably happening is that you haven't update since. Try running an _update --force and it should index all your albums.

**Comment by XpertShadow** [comment]
That did the trick! Appreciate it man.
