### ISSUE TITLE
Exlpr.fm support

### ISSUE THREAD

**Issue by Kephalos5** [ishwi/discordBot#36]
Is there any way you could implement some explr.fm integration?
e.g. Have the bot send an image of you explr.fm map.

**Comment by ishwi** [comment]
Exlpr.fm doesn't have an API so then the only way I could get the resulting image is by using web automation and calculating and parsing the image in the bot server. 
The website makes afaik 1 API call per new artist which would be way too heavy for our side, last.fm  and probably the explr.fm service if we were to provide this functionality. And also it would not be trivial to make, at least for me so I dont think this will be implemented.
