### ISSUE TITLE
last.fm links are broken in globalmatching command

### ISSUE THREAD

**Issue by RaylaLe100** [ishwi/discordBot#38]
I believe globalaffinity and globalmatching had similar displays, but now I can no longer click on the globalmatching links.
![image](https://user-images.githubusercontent.com/48224109/100391650-65d7b480-3034-11eb-8db7-56009e9e340a.png)
(the simple matching command seems to work fine though)

**Comment by ishwi** [comment]
Thanks for taking the time to report the problem!

Should be fixed already with c007e5b456b7b274afcfc1fe7b50253efa2bd344.
